steps:
- id: 'getbash'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "bash"
      
- id: 'tf init'
  name: 'hashicorp/terraform:1.2.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd dev
        terraform init
        
- id: 'tf plan'
  name: 'hashicorp/terraform:1.2.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
        cd dev
          terraform plan
          
- id: 'tf apply'
  name: 'hashicorp/terraform:1.2.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
        cd dev
          terraform apply -auto-approve
