steps:
- id: 'name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "bash"

- id: 'tf init'
  name: 'hashicorp/terraform:1.2.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd dev
        terraform init

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.2.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
        cd dev
          terraform plan
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.2.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
        cd dev
          terraform apply -auto-approve
# [END tf-apply]      
